version: "3.8"
services:
  db:
    container_name: crud_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "BM2106"
      POSTGRES_DB: crud_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: crud_pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: "BM2106"
    ports:
      - "40002:80"
  app:
    build: .
    container_name: crud_go_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: BM2106
      DB_NAME: crud_db